### ISSUE TITLE
missing package unzip on onie-debian9

### ISSUE THREAD

**Issue by deep5050** [CumulusNetworks/DUE#44] opened 2023-11-08 09:35 UTC
configure: error: missing required tool: unzip
make/crosstool-ng.make:92: recipe for target '/home/sonic/onie/build/crosstool-ng/stamp/crosstool-ng-configure' failed
make: *** [/home/sonic/onie/build/crosstool-ng/stamp/crosstool-ng-configure] Error 1
make: *** Waiting for unfinished jobs....
2023-11-08 09:32:06 URL:http://mirror.opencompute.org/onie/crosstool-NG/isl-0.20.tar.xz [1539064/1539064] -> "/home/sonic/onie/build/download/isl-0.20.tar.xz" [1]
  Got          isl-0.20.tar.xz

isl-0.20.tar.xz: OK
==== Getting upstream mpc-1.1.0.tar.gz ====
  Downloading mpc-1.1.0.tar.gz from: http://mirror.opencompute.org/onie/crosstool-NG/mpc-1.1.0.tar.gz
2023-11-08 09:32:08 URL:http://mirror.opencompute.org/onie/crosstool-NG/mpc-1.1.0.tar.gz [701263/701263] -> "/home/sonic/onie/build/download/mpc-1.1.0.tar.gz" [1]
  Got          mpc-1.1.0.tar.gz

mpc-1.1.0.tar.gz: OK
==== Getting upstream mpfr-4.1.0.tar.xz ====
  Downloading mpfr-4.1.0.tar.xz from: http://mirror.opencompute.org/onie/crosstool-NG/mpfr-4.1.0.tar.xz
2023-11-08 09:32:15 URL:http://mirror.opencompute.org/onie/crosstool-NG/mpfr-4.1.0.tar.xz [1525476/1525476] -> "/home/sonic/onie/build/download/mpfr-4.1.0.tar.xz" [1]
  Got          mpfr-4.1.0.tar.xz

mpfr-4.1.0.tar.xz: OK
==== Getting upstream strace-4.26.tar.xz ====
  Downloading strace-4.26.tar.xz from: http://mirror.opencompute.org/onie/crosstool-NG/strace-4.26.tar.xz
2023-11-08 09:32:22 URL:http://mirror.opencompute.org/onie/crosstool-NG/strace-4.26.tar.xz [1444216/1444216] -> "/home/sonic/onie/build/download/strace-4.26.tar.xz" [1]
  Got          strace-4.26.tar.xz

strace-4.26.tar.xz: OK
==== Getting upstream zlib-1.2.11.tar.xz ====
Using cached /home/sonic/onie/build/download/zlib-1.2.11.tar.xz
zlib-1.2.11.tar.xz: OK
sonic@due-onie-build-debian-9:~/onie/build-config$

**Comment by deep5050** [comment] 2023-11-08 09:54
want to work on it

**Comment by ehdoyle** [comment] 2023-11-09 00:20
Hi - I just confirmed that you are correct about it missing, which really surprises me as I'd have thought that would have been spotted immediately in build testing after fixing the last issue with the Debian 9 repositories needing to be patched.
I can get it in there pretty quick.  Can you supply the build commands you were using so I can try and figure out why this was missed in the first place ( i.e. maybe I was building something that didn't need unzip, or a package went from gzip to zip... )
Thanks!

**Comment by ehdoyle** [comment] 2023-11-09 15:09
Do you have your exact build commands - what platform you were trying to build, what branch of ONIE you'd checked out, etc - it seems to be working for me. Thanks!

**Comment by deep5050** [comment] 2023-11-10 06:42
```bash

./due --create --platform linux/amd64    --name onie-build-debian-9     --prompt ONIE-9       --tag onie                    --use-template onie              --from debian:9                              --description "ONIE Build Debian 9"                    --image-patch debian/9/filesystem
/home/tatha/DUE/due-build-merge/onie-build-debian-9
```

host machine:

```bash
tatha@oth-163:~/DUE$ neofetch
            .-/+oossssoo+/-.               tatha@oth-163
        `:+ssssssssssssssssss+:`           -------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.6 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: H81M-S1
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-150-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 11 days, 1 hour, 30 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1809
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.20
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: /dev/pts/4
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel i5-4440 (4) @ 3.300GHz
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   GPU: Intel Xeon E3-1200 v3/4th Gen Core Processor
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 846MiB / 7851MiB
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
tatha@oth-163:~/DUE$

```

ONIE is at `master`
```bash
tatha@due-onie-build-debian-9:~/onie$ git branch
* master
```

**Comment by ehdoyle** [comment] 2023-11-10 15:08
That explains it - you'll want to build the master branch from  a Debian 10 ONIE container.
There's a [json file](https://github.com/opencomputeproject/onie/blob/master/build-config/scripts/onie-build-targets.json) in ONIE that details which platforms build in which environment.

The short explanation is that after the 2021.08 release a bunch of component versions in master were upgraded and only built with the tools available in a Debian 10 environment. Support for Debian 9 (and one Debian 8) container preserved the ability to continue to build older platforms as backporting was not going to happen for a number of reasons.
So even with unzip, you'll most likely encounter compilation issues later on.
(There's a more robust explanation of that  [here](https://www.youtube.com/watch?v=8H4S7eSZWJ4&t=264s) if you're really bored :)

The easy way to create a  Debian 10 based ONIE container:
`due --create --help --filter onie
Filtering output to contain [ onie ]

Example build environments:
Image type        Creation command
---------------------------------------------------------------------------

**onie ./due --create --platform linux/amd64 --name onie-build-debian-10 --prompt ONIE-10 --tag onie-10   --use-template onie --from debian:10 --description "ONIE Build Debian 10"**
onie ./due --create --platform linux/amd64 --name onie-build-debian-11 --prompt ONIE-11 --tag onie-11   --use-template onie --from debian:11 --description "ONIE Build Debian 11"
onie ./due --create --platform linux/amd64 --name onie-build-debian-8  --prompt ONIE-8  --tag onie-8 --use-template onie --from debian:8  --description "ONIE Build Debian 8"
onie ./due --create --platform linux/amd64 --name onie-build-debian-9  --prompt ONIE-9  --tag onie-9   --use-template onie --from debian:9  --description "ONIE Build Debian 9"  --image-patch debian/9/filesystem`

Then just cut and paste the Debian 10 line starting with ./due.
Make sure you're using the ONIE version from GitHub. I don't think it had been upstreamed in to Ubuntu 18, but the one currently in Ubuntu is pretty old.
That should work without issue.
Thanks!

**Comment by ehdoyle** [comment] 2023-11-13 16:47
I'll close this out, but feel free to reopen if that didn't fix the issue. Thanks!

**Closed by ehdoyle** 2023-11-13 16:47 UTC
